from __future__ import annotations

from rc_single_span.verification.gate import (
    CapabilityEvidence,
    EvidenceState,
    VerificationGate,
)


def expanded_legacy_bs_v1_gate() -> VerificationGate:
    """Return the expanded legacy BS 5400 / BD 37 software-capability gate.

    The gate covers the software mechanisms for highway combinations 1-5,
    standard fatigue-vehicle generation and code-defined curtailment extension.
    It does not assert that a particular bridge or every possible secondary
    action has been analysed.  Project-specific horizontal/local response,
    bearing properties, fatigue resistance/detail classification and other
    authority choices remain explicit inputs.
    """

    return VerificationGate(
        (
            CapabilityEvidence(
                capability="legacy_bs_structural_response",
                state=EvidenceState.ACCEPTED,
                evidence=(
                    "Genuine STAAD evidence covers the verified full-width V1 model family, "
                    "including HA, HB and HA+HB: 83/83 models and 410,576/410,576 "
                    "expected direct-global fields with zero engineering comparison failures."
                ),
            ),
            CapabilityEvidence(
                capability="legacy_bs_combinations_1_to_5",
                state=EvidenceState.ACCEPTED,
                evidence=(
                    "BD 37/01 combinations 1-3 remain generated by the primary HA/HB/HA+HB "
                    "engine. Combination 4 now has source-pinned centrifugal, longitudinal "
                    "HA/HB and skidding actions plus an explicit classified-action factor "
                    "interface; combination 5 includes bearing friction at 1.30 ULS / 1.00 "
                    "SLS. Supplementary structural effects must come from an analysis model "
                    "appropriate to the horizontal/local action rather than being fabricated "
                    "by the vertical grillage."
                ),
            ),
            CapabilityEvidence(
                capability="legacy_bs_resistance_serviceability",
                state=EvidenceState.ACCEPTED,
                evidence=(
                    "Legacy flexure, shear and crack-width kernels are independently checked, "
                    "with elastic displacement response externally checked by STAAD and "
                    "project serviceability limits kept explicit."
                ),
            ),
            CapabilityEvidence(
                capability="legacy_bs_fatigue_vehicle",
                state=EvidenceState.ACCEPTED,
                evidence=(
                    "The BS 5400 Part 10 standard highway fatigue vehicle is implemented as "
                    "four 80 kN axles at 1.8/6.0/1.8 m spacing and feeds the existing moving-"
                    "vehicle-to-reinforcement-stress-range engine. Fatigue resistance/detail "
                    "classification remains an explicit project/code input."
                ),
            ),
            CapabilityEvidence(
                capability="legacy_bs_curtailment",
                state=EvidenceState.ACCEPTED,
                evidence=(
                    "The BS 5400-4 clause 5.8.7 continuation rule is implemented as the greater "
                    "of effective depth d and 12 bar diameters beyond the theoretical cutoff, "
                    "while support anchorage remains separately explicit."
                ),
            ),
            CapabilityEvidence(
                capability="legacy_bs_detailing",
                state=EvidenceState.ACCEPTED,
                evidence=(
                    "Source-pinned legacy reinforcement limits, discrete cages/links, station "
                    "zoning, laps, construction-stage stress, end-zone checks, doubly reinforced "
                    "SLS and the resolved standard fatigue/curtailment Stage D wrapper are "
                    "available without borrowing BS EN factors."
                ),
            ),
            CapabilityEvidence(
                capability="legacy_bs_reporting",
                state=EvidenceState.ACCEPTED,
                evidence=(
                    "Calculation/reporting infrastructure preserves code basis, factors, "
                    "provenance and unresolved project inputs rather than silently defaulting "
                    "authority-specific decisions."
                ),
            ),
        )
    )
